### ISSUE TITLE
Ignore keys

### ISSUE THREAD

**Issue by hjylewis** [godaddy/eslint-plugin-i18n-json#16]
Some translation services require metadata included in language files as a property.  It would be great to be able to whitelist properties so that they don't get linted.

For example, right now I'm getting a `Array [] ===> TypeError: An Array cannot be a translation value.` because the metadata includes an array.

**Comment by mayank23** [comment]
Hey @hjylewis 😃, thanks for bringing this up. I’m planning on removing the Array restriction and also including ignore options for each rule. If you have any other possible ideas, please let me know! 😄

**Comment by hjylewis** [comment]
@mayank23 Awesome! I'll let you know. I'm looking forward to using this plugin but the Array restriction is a blocker at the moment.

**Comment by mayank23** [comment]
Hi @hjylewis 😄 . Could you provide an example of what a `metadata` key could look like? Just for curiosity. Thanks! There is an in progress branch atm, hoping to finish it up soon 😄 . `branch:ignore-key-global-setting`

**Comment by hjylewis** [comment]
We use Smartling as a service to translate our language and they require a "smartling" prop in lang files with meta data about the file.

For example,
```js
// es.json
{
  "smartling": {
    "placeholder_format_custom": [ ... ],
	...
  },
  ...
}
```

**Comment by mayank23** [comment]
Awesome, thanks for the info!

**Comment by mayank23** [comment]
hi @hjylewis 😄 , released an update for ignoring keys in the latest v2.4.0 release. https://github.com/godaddy/eslint-plugin-i18n-json#i18n-jsonignore-keys

Currently it's a sort of global setting as mentioned in the README.md . Future updates should turn this into a more granular setting such that it can be controlled on a per rule basis. Thanks!

**Comment by hjylewis** [comment]
Awesome, thanks!
