### ISSUE TITLE
TypeError: Cannot destructure property `value` of 'undefined' or 'null' (valid-json.js:61:15)

### ISSUE THREAD

**Issue by unlight** [godaddy/eslint-plugin-i18n-json#26]
`eslint-plugin-i18n-json\src\valid-json.js:61:15`

![image](https://user-images.githubusercontent.com/301732/64491806-97bcf980-d27d-11e9-834d-1e93ce94d921.png)

**Comment by unlight** [comment]
The issue is that I must separate my lint checks to json and sources.
p4
```
eslint --fix --ext .json --format node_modules/eslint-plugin-i18n-json/formatter.js translations/
```

But it possible to keep all in one?
You can get current filename by
```
const filenameWithExtension = context.getFilename();
```

**Comment by mayank23** [comment]
Hi @unlight , thanks for the issue post! I'll get that added in so we ignore source files. Can you post the original full eslint command you were using to lint both the json and sources? 

Thanks 😄

**Comment by unlight** [comment]
Hi.
I'm using TypeScript and my initial eslint command is `eslint src --ext .ts`, after configuring `i18n-json` I though I can do `eslint src --ext .ts,.json` and see all lint results in one output.

Part of my eslint config is:
```
    root: true,
    env: {
        node: true,
        browser: true,
        jasmine: true,
    },
    extends: [
        'eslint:recommended',
        'plugin:unicorn/recommended',
        'plugin:jasmine/recommended',
        'plugin:ngxs-style-guide/recommended',
    ],
    parser: '@typescript-eslint/parser',
    parserOptions: {
        ecmaVersion: 2019,
        sourceType: 'module',
        ecmaFeatures: {
            jsx: false,
        },
        project: 'tsconfig.json',
    },
```

My current working command to check json is following:
```
    eslint --no-eslintrc --plugin i18n-json --ext .json \
        --rule 'i18n-json/valid-json: [2]' \
        src
```

**Comment by Davekennedy111** [comment]
Having the same issue, any update @mayank23 ?

**Comment by mayank23** [comment]
@Davekennedy111 , will get a fix in today 😄

**Comment by gegham1** [comment]
I'm getting the same error

**Comment by gegham1** [comment]
when you'll fix this ?

**Comment by mayank23** [comment]
hi @gegham1 , actively working on the fix. Hoping to clean up some other parts of the project too hence the delay. Will have a fix this week, just wrapping up some tests now.

**Comment by mayank23** [comment]
This has been fixed in version v2.4.3 and it is now published on npm 😄

**Comment by abouzeyd** [comment]
TypeError: Cannot destructure property `nodes` of 'undefined' or 'null'

**Comment by abouzeyd** [comment]
const MostRead = (props) => {
  const {mostReadCategoryPosts} = props
  const {nodes} = mostReadCategoryPosts

**Comment by mayank23** [comment]
@abouzeyd are you running into this issue?
