### ISSUE TITLE
Nomnom depricated in jsonlint

### ISSUE THREAD

**Issue by tvarsis** [godaddy/eslint-plugin-i18n-json#5]
Gives error on install. Seems to be related to the title and this thread:

https://github.com/zaach/jsonlint/issues/103

**Comment by mayank23** [comment]
Hey @tvarsis  😄, could you post your terminal output? Thanks

**Comment by tvarsis** [comment]
Hi!

Getting this warning:

warning eslint-plugin-i18n-json > jsonlint > nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.

After I rebooted the computer, the package does install now though, but the warning is still there. Before I was getting an error.

**Comment by mayank23** [comment]
Thanks for the info, I'll look for another json linter. (most likely: https://github.com/sindresorhus/parse-json)
